# Generated by Django 5.0 on 2023-12-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Line_App', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
