# Generated by Django 5.0 on 2023-12-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Line_App', '0004_post_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
